// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBE08OzrLD3glKsmjYsiVK2s35nWeNKJo',
    appId: '1:1015172199806:android:eaebe5faf10bf3997aef2f',
    messagingSenderId: '1015172199806',
    projectId: 'reddit-fe218',
    storageBucket: 'reddit-fe218.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBE08OzrLD3glKsmjYsiVK2s35nWeNKJo',
    appId: '1:1015172199806:android:eaebe5faf10bf3997aef2f',
    messagingSenderId: '1015172199806',
    projectId: 'reddit-fe218',
    storageBucket: 'reddit-fe218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Eh9nEKPyiOMUfjysBVuiTSVKSAEdIc4',
    appId: '1:1015172199806:ios:40b3ddc74a8edb7b7aef2f',
    messagingSenderId: '1015172199806',
    projectId: 'reddit-fe218',
    storageBucket: 'reddit-fe218.appspot.com',
    iosBundleId: 'com.example.reddit',
  );
}
